### ISSUE TITLE
Chapter 11 link does not work

### ISSUE THREAD

**Issue by volkandkaya** [IntermediatePython/intermediatePython#42]
You linked to http://docs.python-guide.org/en/latest/dev/virtualenvs.html it gives an error. 

http://python-guide.readthedocs.org/en/latest/dev/virtualenvs works

**Comment by SanketDG** [comment]
Yep, you can't link html pages in sphinx I think
http://docs.python-guide.org/en/latest/dev/virtualenvs will also work.

**Comment by volkandkaya** [comment]
Oh it adds a .html to the end, hopefully they will fix that problem.

**Comment by yasoob** [comment]
Hopefully solved :+1:
